FROM node:20

WORKDIR /app

COPY package*.json ./

RUN npm install && \
    npm install -g @nestjs/cli && \
    npm install -g nodemon && \
    npm install -g ts-node


COPY . .

EXPOSE 3000

CMD ["nodemon", "--watch", "src/**/*", "--ext", "ts", "--exec", "npm run start:dev"]